(defproject org.shark8me/tfevent-sink "0.1.1-SNAPSHOT"
  :description "FIXME: write description"
  :url "http://example.com/FIXME"
  :license {:name "Eclipse Public License"
            :url "http://www.eclipse.org/legal/epl-v10.html"}
  :java-source-paths [;sources generated by protoc compiler
                      "src/java" 
                      ;sources copied from github.com/tensorflow/ecosystem for reading and writing TFRecords
                      "src/java-ecosystem"
                      ]
  :prep-tasks  ["javac" "compile"]
  :source-paths ["src/clojure"]
  :test-paths ["test/clojure"]
  :dependencies [[org.clojure/clojure "1.8.0"]
                 [org.clojars.ghaskins/protobuf "3.0.2-2"]
                 ;[org.clojars.ghaskins/protobuf "3.1.0"]
                 ;; https://mvnrepository.com/artifact/com.google.protobuf/protobuf-java
                 [com.google.protobuf/protobuf-java "3.1.0"]
                [com.rpl/specter "1.0.1"]]
  :javac-options ["-Xmaxerrs" "1000"]
  :javadoc-opts { :package-names ["org.tensorflow.framework"
                  "org.tensorflow.util"]}
  :plugins  [[lein-protobuf "0.1.1"]
             [lein-javadoc "0.3.0"]]
  )
